### ISSUE TITLE
github网站存放deploy_scripts文件夹中多了一个change_res.sh脚本

### ISSUE THREAD

**Issue by PYNewMan** [kunpengcompute/Kbox#13]
◆【现象描述】：github网站存放deploy_scripts文件夹中多了一个change_res.sh脚本
◆【测试步骤】：
P1.版本转测
S1.检查蓝区需求相关代码是否正常在GitHub代码仓，出现结果E1
S2.检查Android镜像编译以及环境部署时涉及的patch的获取链接，出现结果E2
S1.相关开源交付的patch代码正常同步到GitHub代码仓
S2.部署时用到的patch都在蓝区可以获取到（注意：测试时要使用在蓝区获取到的，不要用cmc等黄区路径的组件）
◇【影响评估】：对外发布开源链接中出现了部署未使用的脚本文件，未经过测试，影响产品可靠性、安全性
◇【出现概率】：100%
◇【原因分析】：deploy_scripts文件夹中多了一个change_res.sh脚本，需删除

**Comment by wtgwtg** [comment]
相关脚本已删除

**Comment by PYNewMan** [comment]
经检查，change_res.sh脚本文件已删除，回归通过。
