### ISSUE TITLE
执行日志脚本收集工具失败

### ISSUE THREAD

**Issue by PYNewMan** [kunpengcompute/Kbox#16]
◆【现象描述】：执行日志脚本收集工具收集失败
◆【测试步骤】：
S1.服务器对存在的所有容器执行收集日志脚本，出现结果E1
S2.对压缩包进行解压，对收集的容器的日志进行查看，出现结果E2
S3.对应用堆栈信息的日志进行查看，出现结果E3
S4.对dumpsys日志信息进行查看，出现结果E4
S5.对容器的进程的日志信息，出现结果E5
S6.对系统属性日志信息，出现结果E6
E1.在根目录下的tmp目录，有一cloudphone_log_yyyymmddhhmmss.tar.gz格式的压缩包
E2.有所有容器收集的logcat日志
E3.日志包中有所有容器应用堆栈信息的日志信息
E4.日志包中有所有容器的dumpsys activity，dumpsys meminfo，dumpsys input 收集的日志信息
E5.日志包中有收集的所有容器的进程的日志信息
E6.日志包中有所有容器的getprop收集系统属性日志信息
◇【影响评估】：业务功能
◇【原因分析】：python里安装的docker版本为最新的5.0.1无法使用，换回旧的5.0.0版本无问题。pip安装将指定python-docker版本

**Comment by KnifeeOneOne** [comment]
it seems that we should limite python-docker <= 5.0.0 until bugs have been fixed (https://github.com/docker/docker-py/issues/2885).

**Comment by PYNewMan** [comment]
经获取最新的日志工具中，readme文件指导使用requirement.txt重新安装指定python-docker后，日志可正常收集，测试回归通过
