### ISSUE TITLE
查询容器版本号信息并非最新，与转测版本号不一致

### ISSUE THREAD

**Issue by PYNewMan** [kunpengcompute/Kbox#17]
◆：必填项；◇：选填项

============基本信息================
◆【测试版本】：Kunpeng Computing Media 2.0.0.B010
◆【定位人员】：万衎震
◆【初步结论】：容器的版本号信息没有更新
◆【严重程度】：一般
◆【发现阶段】：系统设计验证(SDV)
◆【应发现阶段】：story测试
===========问题信息================
◆【现象描述】：查询容器版本号信息并非最新，与转测版本号不一致
◆【测试步骤】：
S1.对正常运行的容器，执行命令docker exec -it kbox_[容器号] getprop |grep ro.product.kbox.version，出现结果E1
E1.能回显比如：ro.product.kbox.version=2.0.0 的最新版本号信息
概率：100%
◇【影响评估】：功能
◇【原因分析】：版本号未更新

============配置信息================
◇【测试组网】：

**Comment by KnifeeOneOne** [comment]
DONE

**Comment by PYNewMan** [comment]
通过查询版本号命令查询版本信息，为最新版本信息，问题单回归通过
