### ISSUE TITLE
容器运行光遇游戏，游戏中部分图标显示异常

### ISSUE THREAD

**Issue by PYNewMan** [kunpengcompute/Kbox#18]
◆：必填项；◇：选填项

============基本信息================
◆【测试版本】：Kunpeng Computing Media 2.0.0.B010
◆【定位人员】：周鸿利
◆【初步结论】：问题在定位中
◆【严重程度】：一般
◆【发现阶段】：系统设计验证(SDV)
◆【应发现阶段】：
===========问题信息================
◆【现象描述】：在该版本的容器运行光遇游戏，游戏中部分图标显示异常。在使用RC2版本的容器运行最新版的光遇游戏，游戏中同样部分图标显示异常。而在RC2版本测试中，旧版本游戏运行画面正常。
◆【测试步骤】：
S1.使用镜像启动容器，并在容器上安装光遇游戏，运行10min，出现结果E1
E1.光遇游戏正常运行，无运行异常，画面异常，花屏，卡顿，掉帧等现象
概率：100%复现
◇【影响评估】：功能
◇【原因分析】：问题在定位中

============配置信息================
◇【测试组网】：

**Comment by biglecat** [comment]
该问题转需求，见需求跟踪表。路径：智能计算/Kunpeng Computing DC Solution/Docs/Kunpeng Computing Media 2/02.系统组/04.版本CCB/Kunpeng Computing Media 2解决方案CCB问题单转需求跟踪总表.xls

**Comment by PYNewMan** [comment]
关闭类型: 问题解决关闭
应触发因素(级联):  Story验证/Story测试/正常路径

【回归版本号】
Kunpeng Computing Media 2.0.0.B022
【回归测试步骤及测试项】
S1.使用镜像启动容器，并在容器上安装光遇游戏，运行10min，出现结果E1
E1.光遇游戏正常运行，无运行异常，画面异常，花屏，卡顿，掉帧等现象
【回归测试现象】
此问题单转需求，问题单关闭。
