### ISSUE TITLE
容器打开光遇游戏，有概率会出现游戏闪退返回桌面的现象

### ISSUE THREAD

**Issue by PYNewMan** [kunpengcompute/Kbox#21]
◆：必填项；◇：选填项

============基本信息================
◆【测试版本】：Kunpeng Computing Media 2.0.0.B020
◆【定位人员】：周鸿利
◆【初步结论】：可能vulkan那一块的适配没到位，还存在些问题；也有可能是音频的问题 Kbox不支持音频 闪退前的报错日志打了一段音频相关的；具体问题在定位中
◆【严重程度】：一般
◆【发现阶段】：系统集成测试(SIT)
◆【应发现阶段】：
===========问题信息================
◆【现象描述】：在该版本的容器运行光遇游戏，游戏中部分图标显示异常。在使用RC2版本的容器运行最新版的光遇游戏，游戏中同样部分图标显示异常。而在RC2版本测试中，旧版本游戏运行画面正常。
◆【测试步骤】：
S1.使用镜像启动容器，并在容器上安装光遇游戏，运行10min，出现结果E1
E1.光遇游戏正常运行，无运行异常，画面异常，花屏，卡顿，掉帧等现象
概率：33%复现
◇【影响评估】：功能
◇【原因分析】：问题在定位中

============配置信息================
◇【测试组网】：

**Comment by biglecat** [comment]
应触发因素（级联）：Story验证/Story测试/正常路径
1、该问题属安卓9版本音频流内存申请释放相关的原生问题，该部分在安卓高版本已经被官方修改并加固，
2、结论是在兼容性列表中添加共性约束. 后续升级高版本安卓解决。
约束见B022版本CMC链接中Kunpeng Computing Media 2.0.0 Kbox安卓容器 版本配套表.xlsx

**Comment by PYNewMan** [comment]
关闭类型: 问题解决关闭
应触发因素(级联):  Story验证/Story测试/正常路径

【回归版本号】
Kunpeng Computing Media 2.0.0.B022
【回归测试步骤及测试项】
S1.使用镜像启动容器，并在容器上安装光遇游戏，运行10min，出现结果E1
E1.光遇游戏正常运行，无运行异常，画面异常，花屏，卡顿，掉帧等现象
【回归测试现象】
在兼容性列表中添加共性约束，后续升级高版本安卓解决，问题单关闭
