### ISSUE TITLE
执行日志脚本收集工具收集的日志不在既定的tmp目录下

### ISSUE THREAD

**Issue by PYNewMan** [kunpengcompute/Kbox#6]
◆【现象描述】：执行日志脚本收集工具收集的日志不在既定的tmp目录下
◆【测试步骤】：
S1.服务器对存在的所有容器执行收集日志脚本，出现结果E1
S2.对压缩包进行解压，对收集的容器的日志进行查看，出现结果E2
S3.对应用堆栈信息的日志进行查看，出现结果E3
S4.对dumpsys日志信息进行查看，出现结果E4
S5.对容器的进程的日志信息，出现结果E5
S6.对系统属性日志信息，出现结果E6
E1.在根目录下的tmp目录，有一cloudphone_log_yyyymmddhhmmss.tar.gz格式的压缩包
E2.有所有容器收集的logcat日志
E3.日志包中有所有容器应用堆栈信息的日志信息
E4.日志包中有所有容器的dumpsys activity，dumpsys meminfo，dumpsys input 收集的日志信息
E5.日志包中有收集的所有容器的进程的日志信息
E6.日志包中有所有容器的getprop收集系统属性日志信息
◇【影响评估】：业务功能
◇【出现概率】：100%
◇【原因分析】：放在tmp目录可能有误删除的风险，实际路径和需求说明以及特性设计说明书不符

**Comment by KnifeeOneOne** [comment]
已修改特性设计描述，具体可查看相关文档

**Comment by PYNewMan** [comment]
收集的日志已更改存放至收集脚本同级目录，问题解决，回归通过
